version: '3.8'

services:
  svelteapp:
    container_name: svelte_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    volumes:
      - .:/app    
    environment:
      - NODE_ENV=development  
